[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

# Next.js on Netlify configuration
[functions]
  node_bundler = "esbuild"

# Handle Next.js routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200